### ISSUE TITLE
Issue w/ GitLab

### ISSUE THREAD

**Issue by Chaprnks** [WakeupNeo33/Anti-AdBlocker-Fuckoff-userscript#2]
I just noticed this userscript has an odd issue with browsing GitLab repos. After loading, it completely hides the whole GitLab UI of any repo.

Example:
![GbJQxap](https://user-images.githubusercontent.com/6340970/119210136-bd515d00-ba78-11eb-84ea-a3e1efcdf58f.png)
![451pQ4c](https://user-images.githubusercontent.com/6340970/119210137-be828a00-ba78-11eb-9361-4b1ab9d67e12.png)

**Comment by RuiGuilherme** [comment]
Very strange, that doesn't happen on every page. 
![image](https://user-images.githubusercontent.com/17581421/119729773-91f9b400-be64-11eb-9b89-0fed5bbcc39b.png)

Fast fix: you just need add gitlab to excluded domains: 
![image](https://user-images.githubusercontent.com/17581421/119730311-19dfbe00-be65-11eb-8835-2bec77a2a7fd.png)

**Comment by WakeupNeo33** [comment]
Thanks @Chaprnks. 
github.com and gitlab.com added to excluded domains in version 1.4.1

and thanks @RuiGuilherme  for your help
